version: '3.8'

services:
  postgreSQL:
    env_file: .env
    image: postgres:12.17
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    restart: always
    volumes:
      - ktrek_database:/var/lib/postgresql/data
    networks:
      - ktrek

volumes:
  ktrek_database:

networks:
  ktrek:
    external: true
